clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型参数，边界条件输入
[dimension,dettx,m,length_x,length_y,length_z,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,detla,cf,cm,volume_particle,size_horizon_particle, ...
    boundary_condition_left,boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,displacement_left, ...
    displacement_right,displacement_bottom,displacement_top,displacement_behind,displacement_front,uniform_load_left,uniform_load_right,uniform_load_bottom, ...
    uniform_load_top,uniform_load_behind,uniform_load_front,det_displacement_left,det_displacement_right,det_displacement_bottom,det_displacement_top,det_displacement_behind, ...
    det_displacement_front,det_uniform_load_left,det_uniform_load_right,det_uniform_load_bottom,det_uniform_load_top,det_uniform_load_behind,det_uniform_load_front, ...
    body_force,initial_crack,xx1_crack,yy1_crack,zz1_crack,xx2_crack,yy2_crack,zz2_crack,sf,sm,nt,output_interval,theta]=function_input();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型离散
[particle,size_particle,size_x,size_y,size_z,size_displacement_boundary_left,particle_boundary_left,size_displacement_boundary_right,particle_boundary_right, ...
          size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top,particle_boundary_top,size_displacement_boundary_behind, ...
          particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front,size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right, ...
          particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom,size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind, ...
          particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front,size_particle_damage,particle_damage]=function_discretization(dimension,boundary_condition_left, ...
          boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,length_x,length_y,length_z,dettx,m); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 域内粒子
horizon_particle=function_horizon_particle(particle,size_particle,size_horizon_particle,detla,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 键的分类
[classify_bond]=function_classify_bond(particle,size_particle,size_horizon_particle,horizon_particle,theta,dettx);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 初始裂纹
damage_particle=function_initial_crack(particle,size_particle,horizon_particle,size_horizon_particle,dimension,initial_crack,xx1_crack,yy1_crack,zz1_crack,xx2_crack,yy2_crack,zz2_crack,dettx);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 按总增量步数进行循环
for itime=1:nt
    itime
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 总体刚度矩阵
    [global_stiffness_matrix]=function_global_stiffness_matrix(particle,size_particle,horizon_particle,size_horizon_particle,cf,cm,volume_particle,damage_particle,classify_bond);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %施加边界条件并进行静力学求解                                             
    global_displacement_vector=function_displacement_solution(dimension,size_particle,global_stiffness_matrix,size_displacement_boundary_left,particle_boundary_left, ...
         size_displacement_boundary_right,particle_boundary_right,size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top, ...
         particle_boundary_top,size_displacement_boundary_behind,particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front, ...
         size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right,particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom, ...
         size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind,particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front, ...
         displacement_left,displacement_right,displacement_bottom,displacement_top,displacement_behind,displacement_front,uniform_load_left,uniform_load_right, ...
         uniform_load_bottom,uniform_load_top,uniform_load_behind,uniform_load_front,det_displacement_left,det_displacement_right,det_displacement_bottom, ...
         det_displacement_top,det_displacement_behind,det_displacement_front,det_uniform_load_left,det_uniform_load_right,det_uniform_load_bottom, ...
         det_uniform_load_top,det_uniform_load_behind,det_uniform_load_front,body_force,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
         boundary_condition_top,boundary_condition_behind,boundary_condition_front,volume_particle,itime,output_interval);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 模型损伤计算
    [damage,max_sf,max_sm,damage_particle]=function_damage_solution(particle,size_particle,horizon_particle, ...
    size_horizon_particle,global_displacement_vector,damage_particle,sf,sm,itime,output_interval,size_particle_damage,particle_damage,classify_bond);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end
% 结果可视化
function_visualization(dimension,size_x,size_y,size_z,global_displacement_vector,damage);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


