clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型参数，边界条件输入
[dimension,dettx,m,length_x,length_y,length_z,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,detla,c0,volume_particle,size_horizon_particle, ...
    boundary_condition_left,boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,temperature_left, ...
    temperature_right,temperature_bottom,temperature_top,temperature_behind,temperature_front,heat_flux_left,heat_flux_right,heat_flux_bottom, ...
    heat_flux_top,heat_flux_behind,heat_flux_front,body_heat_source]=function_input();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型离散
[particle,size_particle,size_x,size_y,size_z,size_temperature_boundary_left,particle_boundary_left,size_temperature_boundary_right,particle_boundary_right, ...
          size_temperature_boundary_bottom,particle_boundary_bottom,size_temperature_boundary_top,particle_boundary_top,size_temperature_boundary_behind, ...
          particle_boundary_behind,size_temperature_boundary_front,particle_boundary_front,size_heat_flux_left,particle_heat_flux_left,size_heat_flux_right, ...
          particle_heat_flux_right,size_heat_flux_bottom,particle_heat_flux_bottom,size_heat_flux_top,particle_heat_flux_top,size_heat_flux_behind, ...
          particle_heat_flux_behind,size_heat_flux_front,particle_heat_flux_front]=function_discretization(dimension,boundary_condition_left, ...
          boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,length_x,length_y,length_z,dettx,m); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 域内粒子
horizon_particle=function_horizon_particle(particle,size_particle,size_horizon_particle,detla,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 总体刚度矩阵
global_heat_conduction_matrix=function_global_heat_conduction_matrix(particle,size_particle,horizon_particle,size_horizon_particle,c0,volume_particle,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%施加边界条件并进行静力学求解                                             
global_temperature_vector=function_temperature_solution(dimension,size_particle,global_heat_conduction_matrix,size_temperature_boundary_left,particle_boundary_left, ...
         size_temperature_boundary_right,particle_boundary_right,size_temperature_boundary_bottom,particle_boundary_bottom,size_temperature_boundary_top, ...
         particle_boundary_top,size_temperature_boundary_behind,particle_boundary_behind,size_temperature_boundary_front,particle_boundary_front, ...
         size_heat_flux_left,particle_heat_flux_left,size_heat_flux_right,particle_heat_flux_right,size_heat_flux_bottom,particle_heat_flux_bottom, ...
         size_heat_flux_top,particle_heat_flux_top,size_heat_flux_behind,particle_heat_flux_behind,size_heat_flux_front,particle_heat_flux_front, ...
         temperature_left,temperature_right,temperature_bottom,temperature_top,temperature_behind,temperature_front,heat_flux_left,heat_flux_right, ...
         heat_flux_bottom,heat_flux_top,heat_flux_behind,heat_flux_front,body_heat_source,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
         boundary_condition_top,boundary_condition_behind,boundary_condition_front,volume_particle,dettx);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 结果可视化
function_temperature_visualization(dimension,size_x,size_y,size_z,global_temperature_vector);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


