clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型参数，边界条件输入
[E0,dimension,dettx,m,length_x,length_y,length_z,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,detla,c0,volume_particle,size_horizon_particle, ...
    boundary_condition_left,boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,displacement_left, ...
    displacement_right,displacement_bottom,displacement_top,displacement_behind,displacement_front,uniform_load_left,uniform_load_right,uniform_load_bottom, ...
    uniform_load_top,uniform_load_behind,uniform_load_front,body_force]=function_input();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型离散
[particle,size_particle,size_x,size_y,size_z,size_displacement_boundary_left,particle_boundary_left,size_displacement_boundary_right,particle_boundary_right, ...
          size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top,particle_boundary_top,size_displacement_boundary_behind, ...
          particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front,size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right, ...
          particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom,size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind, ...
          particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front]=function_discretization(dimension,boundary_condition_left, ...
          boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,length_x,length_y,length_z,dettx,m); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 域内粒子
horizon_particle=function_horizon_particle(particle,size_particle,size_horizon_particle,detla,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 总体刚度矩阵
global_stiffness_matrix=function_global_stiffness_matrix(particle,size_particle,horizon_particle,size_horizon_particle,c0,volume_particle,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%施加边界条件并进行静力学求解                                             
global_displacement_vector=function_displacement_solution(dimension,size_particle,global_stiffness_matrix,size_displacement_boundary_left,particle_boundary_left, ...
         size_displacement_boundary_right,particle_boundary_right,size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top, ...
         particle_boundary_top,size_displacement_boundary_behind,particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front, ...
         size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right,particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom, ...
         size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind,particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front, ...
         displacement_left,displacement_right,displacement_bottom,displacement_top,displacement_behind,displacement_front,uniform_load_left,uniform_load_right, ...
         uniform_load_bottom,uniform_load_top,uniform_load_behind,uniform_load_front,body_force,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
         boundary_condition_top,boundary_condition_behind,boundary_condition_front,volume_particle);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 结果可视化
function_visualization(dimension,size_x,size_y,size_z,global_displacement_vector);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


