clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型参数，边界条件输入
[dimension,dettx,m,length_x,length_y,length_z,thick,size_ply,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,detla,cf,cm,bn,bs,volume_particle,size_horizon_particle,size_horizon_particle_n,size_horizon_particle_s, ...
    boundary_condition_left,boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,velocity_left, ...
    velocity_right,velocity_bottom,velocity_top,velocity_behind,velocity_front,uniform_load_left,uniform_load_right,uniform_load_bottom, ...
    uniform_load_top,uniform_load_behind,uniform_load_front,body_force,theta,detla_n,detla_s,dt,time,output_interval,density,nt]=function_input();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型离散
[particle,size_particle,size_x,size_y,size_z,size_displacement_boundary_left,particle_boundary_left,size_displacement_boundary_right,particle_boundary_right, ...
          size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top,particle_boundary_top,size_displacement_boundary_behind, ...
          particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front,size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right, ...
          particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom,size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind, ...
          particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front,particle_ply,global_velocity_vector,global_displacement_vector]=function_discretization(boundary_condition_left, ...
          boundary_condition_right,boundary_condition_bottom,boundary_condition_top,xx_min,yy_min,zz_min,xx_max,yy_max,length_x,length_y,dettx,m,thick,size_ply,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 域内粒子
[horizon_particle,horizon_particle_n,horizon_particle_s_lower,horizon_particle_s_upper]=function_horizon_particle(particle,size_particle,size_horizon_particle,detla,size_horizon_particle_n,size_horizon_particle_s,dettx,thick);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 键的分类
[classify_bond]=function_classify_bond(particle,size_particle,size_horizon_particle,horizon_particle,theta,dettx,particle_ply);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 按总增量步数进行循环
for itime=1:nt
    itime
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %施加边界条件并进行静力学求解                                             
    [global_velocity_vector,global_displacement_vector]=function_displacement_solution(dimension,size_particle,size_displacement_boundary_left,particle_boundary_left, ...
         size_displacement_boundary_right,particle_boundary_right,size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top, ...
         particle_boundary_top, ...
         size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right,particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom, ...
         size_uniform_load_top,particle_uniform_load_top, ...
         velocity_left,velocity_right,velocity_bottom,velocity_top,uniform_load_left,uniform_load_right, ...
         uniform_load_bottom,uniform_load_top,body_force,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
         boundary_condition_top,itime,dt,output_interval,particle,horizon_particle,size_horizon_particle,cf,cm,bn,bs,density, ...
         global_velocity_vector,global_displacement_vector,volume_particle,classify_bond,horizon_particle_n,size_horizon_particle_n, ...
         horizon_particle_s_lower,horizon_particle_s_upper,detla_n,detla_s,particle_ply);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 结果可视化
function_displacement_visualization(dimension,size_x,size_y,size_z,global_displacement_vector);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%









% % 总体刚度矩阵
% [global_stiffness_matrix]=function_global_stiffness_matrix(particle,size_particle,horizon_particle,size_horizon_particle,horizon_particle_n,size_horizon_particle_n, ...
%     horizon_particle_s_lower,horizon_particle_s_upper,cf,cm,bn,bs,volume_particle,classify_bond,detla_n,detla_s,particle_ply);
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %施加边界条件并进行静力学求解                                             
% global_displacement_vector=function_displacement_solution(dimension,size_particle,global_stiffness_matrix,size_displacement_boundary_left,particle_boundary_left, ...
%          size_displacement_boundary_right,particle_boundary_right,size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top, ...
%          particle_boundary_top,size_displacement_boundary_behind,particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front, ...
%          size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right,particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom, ...
%          size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind,particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front, ...
%          displacement_left,displacement_right,displacement_bottom,displacement_top,displacement_behind,displacement_front,uniform_load_left,uniform_load_right, ...
%          uniform_load_bottom,uniform_load_top,uniform_load_behind,uniform_load_front,body_force,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
%          boundary_condition_top,boundary_condition_behind,boundary_condition_front,volume_particle);
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % 结果可视化
% function_displacement_visualization(dimension,size_x,size_y,size_z,global_displacement_vector);
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


