clear
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型参数，边界条件输入
[dimension,dettx,m,length_x,length_y,length_z,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,detla,c0,volume_particle,size_horizon_particle, ...
    boundary_condition_left,boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,velocity_left, ...
    velocity_right,velocity_bottom,velocity_top,velocity_behind,velocity_front,uniform_load_left,uniform_load_right,uniform_load_bottom, ...
    uniform_load_top,uniform_load_behind,uniform_load_front,body_force,c0_temperature,boundary_condition_left_temperature,boundary_condition_right_temperature, ...
    boundary_condition_bottom_temperature,boundary_condition_top_temperature,boundary_condition_behind_temperature,boundary_condition_front_temperature,temperature_left, ...
    temperature_right,temperature_bottom,temperature_top,temperature_behind,temperature_front,heat_flux_left,heat_flux_right,heat_flux_bottom, ...
    heat_flux_top,heat_flux_behind,heat_flux_front,body_heat_source,alf,temperature_initial,cv,dt,output_interval,density,nt]=function_input();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 模型离散
[particle,size_particle,size_x,size_y,size_z,size_displacement_boundary_left,particle_boundary_left,size_displacement_boundary_right,particle_boundary_right, ...
          size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top,particle_boundary_top,size_displacement_boundary_behind, ...
          particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front,size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right, ...
          particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom,size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind, ...
          particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front, ...
          size_temperature_boundary_left,particle_boundary_left_temperature,size_temperature_boundary_right,particle_boundary_right_temperature, ...
          size_temperature_boundary_bottom,particle_boundary_bottom_temperature,size_temperature_boundary_top,particle_boundary_top_temperature,size_temperature_boundary_behind, ...
          particle_boundary_behind_temperature,size_temperature_boundary_front,particle_boundary_front_temperature,size_heat_flux_left,particle_heat_flux_left,size_heat_flux_right, ...
          particle_heat_flux_right,size_heat_flux_bottom,particle_heat_flux_bottom,size_heat_flux_top,particle_heat_flux_top,size_heat_flux_behind, ...
          particle_heat_flux_behind,size_heat_flux_front,particle_heat_flux_front,global_velocity_vector,global_displacement_vector,global_temperature_vector]=function_discretization(dimension,boundary_condition_left, ...
          boundary_condition_right,boundary_condition_bottom,boundary_condition_top,boundary_condition_behind,boundary_condition_front,xx_min,yy_min,zz_min,xx_max,yy_max,zz_max,length_x,length_y,length_z,dettx,m, ...
          boundary_condition_left_temperature,boundary_condition_right_temperature, ...
    boundary_condition_bottom_temperature,boundary_condition_top_temperature,boundary_condition_behind_temperature,boundary_condition_front_temperature,temperature_initial); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 域内粒子
horizon_particle=function_horizon_particle(particle,size_particle,size_horizon_particle,detla,dimension);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 按总增量步数进行循环
for itime=1:nt
    itime
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %施加边界条件并对温度进行求解                                             
    [global_temperature_vector]=function_temperature_solution(dimension,size_particle,size_temperature_boundary_left,particle_boundary_left_temperature, ...
         size_temperature_boundary_right,particle_boundary_right_temperature,size_temperature_boundary_bottom,particle_boundary_bottom_temperature,size_temperature_boundary_top, ...
         particle_boundary_top_temperature,size_temperature_boundary_behind,particle_boundary_behind_temperature,size_temperature_boundary_front,particle_boundary_front_temperature, ...
         size_heat_flux_left,particle_heat_flux_left,size_heat_flux_right,particle_heat_flux_right,size_heat_flux_bottom,particle_heat_flux_bottom, ...
         size_heat_flux_top,particle_heat_flux_top,size_heat_flux_behind,particle_heat_flux_behind,size_heat_flux_front,particle_heat_flux_front, ...
         temperature_left,temperature_right,temperature_bottom,temperature_top,temperature_behind,temperature_front,heat_flux_left,heat_flux_right, ...
         heat_flux_bottom,heat_flux_top,heat_flux_behind,heat_flux_front,body_heat_source,boundary_condition_left_temperature,boundary_condition_right_temperature,boundary_condition_bottom_temperature, ...
         boundary_condition_top_temperature,boundary_condition_behind_temperature,boundary_condition_front_temperature,dettx, ...
     global_temperature_vector,itime,density,c0_temperature,cv,particle,horizon_particle,size_horizon_particle,dt,output_interval);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %施加边界条件并对位移进行求解 
    [global_velocity_vector,global_displacement_vector]=function_displacement_solution(dimension,size_particle,size_displacement_boundary_left,particle_boundary_left, ...
         size_displacement_boundary_right,particle_boundary_right,size_displacement_boundary_bottom,particle_boundary_bottom,size_displacement_boundary_top, ...
         particle_boundary_top,size_displacement_boundary_behind,particle_boundary_behind,size_displacement_boundary_front,particle_boundary_front, ...
         size_uniform_load_left,particle_uniform_load_left,size_uniform_load_right,particle_uniform_load_right,size_uniform_load_bottom,particle_uniform_load_bottom, ...
         size_uniform_load_top,particle_uniform_load_top,size_uniform_load_behind,particle_uniform_load_behind,size_uniform_load_front,particle_uniform_load_front, ...
         velocity_left,velocity_right,velocity_bottom,velocity_top,velocity_behind,velocity_front,uniform_load_left,uniform_load_right, ...
         uniform_load_bottom,uniform_load_top,uniform_load_behind,uniform_load_front,body_force,boundary_condition_left,boundary_condition_right,boundary_condition_bottom, ...
         boundary_condition_top,boundary_condition_behind,boundary_condition_front,itime,dt,output_interval,particle,horizon_particle,size_horizon_particle,c0,density, ...
         global_velocity_vector,global_displacement_vector,volume_particle,alf,global_temperature_vector,temperature_initial);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 位移结果可视化
function_displacement_visualization(dimension,size_x,size_y,size_z,global_displacement_vector);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 温度结果可视化
function_temperature_visualization(dimension,size_x,size_y,size_z,global_temperature_vector);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


